blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.all_blogs, name="all_blogs"),
    path("<int:blog_id>/", views.detail, name="detail"),
]

personal_portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from portfolio import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls"), name="blog"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to="portfolio/images/")
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_object_or_404, render

from .models import Blog


# Create your views here.
def all_blogs(request):
    blog_count = Blog.objects.count()
    all_blogs = Blog.objects.order_by("date")[:5]
    return render(
        request,
        "blog/all_blogs.html",
        {"all_blogs": all_blogs, "blog_count": blog_count},
    )


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, "blog/detail.html", {"blog": blog})

portfolio/views.py
from django.shortcuts import render

from .models import Project


# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, "portfolio/home.html", {"projects": projects})


def about(request):
    theauthor = "bruvio"
    return render(request, "portfolio/about.html", {"user": theauthor})

blog/templates/blog/all_blogs.html
{% extends  'portfolio/base.html' %}

{% block content  %}
Hello blog

<h2>{{ blog_count }} blog{{ blog_count|pluralize }} written</h2>


<!-- <div class="container text-center"> -->
    <h1>bruvio blog</h1>
    <a href="{% url 'about' %}">About page</a>
    <br>
    <br>
    {% for blog in all_blogs %}

    <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title  }}</h2></a>
    <p>{{ blog.date|date:'M d Y'|upper  }}</p>
    <p>{{ blog.description|striptags|truncatechars:100  }}</p>


    {% endfor %}




<!-- </div> -->
{% endblock %}

blog/templates/blog/detail.html
{% extends  'portfolio/base.html' %}

{% block content  %}

<h1>{{ blog.title }}</h1>

<h2>---{{ blog.date|date:'F j S Y'}}---</h2>

{{ blog.description |safe }}
{% endblock %}

portfolio/templates/portfolio/about.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<div class="container text-center">
<h1>About</h1>
<br>

the author of this web page is
<h2> {{ user }}</h2>
<a href="{% url 'home' %}">Home</a>
</div>

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/serpent.jpeg" %}">

  <title>bruvio</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/serpent.jpeg" %}" width="30" height="30" class="d-inline-block align-top" alt="bruvio's logo">
        <span>bruvio</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/bruno-viola/" target="_blank">LinkedIn</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/------" target="_blank">Twitter</a>
          </li> -->
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
    <div class="col-5">
      <img src="{% static 'portfolio/vaccinato.jpeg' %}" class="img-fluid">
    </div>
  </div>

  <div class="row justify-content-center mb-3">
    <div class="col-md-9 text-center">
      <h1 id="hometext" class="font-weight-bold">bruvio lallero</h1>
    </div>
  </div>

    <h2 class="mt-5">Portfolio</h2>
    <hr>
    <div class="row">
      {% for project in projects %}
      <div class="col-lg-4 col-md-6">

        {% if project.url %}
        <a href="{{ project.url }}">
          <img src="{{ project.image.url }}" class="img-fluid mb-2">
        </a>
        {% else %}

        <img src="{{ project.image.url }}" class="img-fluid mb-2">
        {% endif %}
        <h3>{{ project.title }}</h3>
        <p>{{ project.description }}</p>

      </div>
      {% endfor %}
    </div>


{% endblock %}